#!/bin/bash
### SBATCH --partition=debug
###SBATCH --partition=general
### SBATCH --partition=lo-core # This can be as long as 7 days
#SBATCH --partition=priority
#SBATCH --account=chl23026      # chl23026
#SBATCH --qos=chl23026          # chl23026, me_epyc
#SBATCH --constraint=epyc128 # This is optional
#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --time=07-00:00:00
#SBATCH --mail-user=duc.nguyen@uconn.edu      # Destination email address
#SBATCH --mail-type=END                       # Event(s) that triggers email notification
#SBATCH --job-name=channelflow_job
#SBATCH --output=channelflow_output_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp

##the slurm number to restart simulation... This need full state to be stored.
SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=/scratch/chl23026/jms24002/channelflow_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r {./ddc,makefile,CMakeLists.txt,submit_channelflow_uconn,./inputfields}  "$WORKDIR" && cd "$WORKDIR" || exit -1

source activate base
conda activate channelflow

make builduconn

# mpiexec -n $SLURM_NTASKS ./build/modules/ddc/programs/ddc_findsoln -eqb -Pr 10 -Ra 1000000 -Le 100 -Rr 2 -Ua -0.5 -Ub 0.5 -Ta 1 -Tb 0 -Sa 1 -Sb 0 -dt 1e-3 inputfields/u6 inputfields/t6 inputfields/s6

# this is for case 3 in Yang2021JFM for testing
# mpiexec -n $SLURM_NTASKS ./build/modules/ddc/programs/ddc_simulateflow -m "yang2021jfm" -o "yang2021jfm_case3_2d/" -Pr 10 -Ra 1000000 -Le 100 -Ri 1 -Rr 0.5 -Nx 384 -Ny 385 -Nz 6 -Lx 2 -Lz 0.004 -Ua -0.5 -Ub 0.5 -Ta 1 -Tb 0 -Sa 1 -Sb 0 -dt 2.5e-3 -dtmin 1e-9 -dtmax 1e-2 -dT 10 -T 4000

# this is for case 5 in Yang2021JFM to validate code channelflow_ddc 
mpiexec -n $SLURM_NTASKS ./build/modules/ddc/programs/ddc_simulateflow -m "yang2021jfm_case5" -o "yang2021jfm_case5_2d/" -Pr 10 -Ra 1e7 -Le 100 -Ri 1 -Rr 0.5 -Nx 768 -Ny 385 -Nz 6 -Lx 4 -Lz 0.004 -Ua -0.5 -Ub 0.5 -Ta 1 -Tb 0 -Sa 1 -Sb 0 -dt 2.5e-3 -dtmin 1e-9 -dtmax 1e-2 -dT 10 -T 6000


cd "$SUBMITDIR" && cp channelflow_output_$SLURM_JOB_ID "$WORKDIR"

